
language: go

branches:
  only:
  - master

stages:
  - test
  - name: release
    if: branch = master

matrix:
  include:
    - name: "Linux Tests"
      env: P_PREFIX=/usr/home
      os: linux
    - name: "OSX Tests"
      env: P_PREFIX=/usr/home
      os: osx
    - name: "Windows Tests"
      env: P_PREFIX=C:\p
      os: windows
    - if: branch = master
      name: "Build for all Platforms"
      stage: release
      os: linux
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then make release; fi'

      
before_script:
  # get dependencies
  - go get ./...

script:
  - go build ./cmd/gop
  - gop --version && gop --help
